/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "e82a658d8159cabbd4938c1660f9bb00b4a82a23"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
