/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "5b78d137d0b64a11abb4e9e67c74ca0396bc59c6"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
