/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "a21f10dd8b19c6cb47d07d94d0a0525c16461969"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
