/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "cef1ea7830d19987bd9fa1794e0be91bb38d382c-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
