/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "e3917fd5ca950222facf027a73d95c8339bced54"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
